GO_EASY_ON_ME = 1
include ../theos/makefiles/common.mk
export ARCHS = armv7 armv7s
TWEAK_NAME = actHack
actHack_FILES = actHack.xm
actHack_FRAMEWORKS = AVFoundation UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
