GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 armv7s arm64

TWEAK_NAME = actHack
actHack_FILES = actHack.xm
actHack_FRAMEWORKS = AVFoundation UIKit

include ../theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
