GO_EASY_ON_ME = 1

SDKVERSION = 6.0
ARCHS = armv7

TWEAK_NAME = actHack6
actHack6_FILES = actHack6.xm
actHack6_FRAMEWORKS = UIKit
actHack6_PRIVATE_FRAMEWORKS = PhotoLibraryServices

include ../theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
