GO_EASY_ON_ME = 1
ARCHS = armv7 armv7s arm64
include ../theos/makefiles/common.mk

LIBRARY_NAME = PanoHook7
PanoHook7_FILES = Hooks.c
PanoHook7_FRAMEWORKS = CoreFoundation
PanoHook7_LIBRARIES = MobileGestalt

include $(THEOS_MAKE_PATH)/library.mk
