
include ../theos/makefiles/common.mk
export ARCHS = armv7
TWEAK_NAME = celestialHook
celestialHook_FILES = celestialHook.xm
celestialHook_PRIVATE_FRAMEWORKS = Celestial

include $(THEOS_MAKE_PATH)/tweak.mk
