#!/bin/bash

declare -a cydia
cydia=($CYDIA)
chk=$(uname -m)

if [[ $1 == install ]]; then
	if [[ "$chk" == "iPhone2,1" ]] || [[ "$chk" == iPhone3* ]] || [[ "$chk" == "iPod4,1" ]] || [[ "$chk" == iPad2* ]] || [[ "$chk" == iPad3* ]]; then
   		PanoInstaller
   		if [ $? = 0 ]; then
        	if [[ ${CYDIA+@} ]]; then
          		eval "echo 'finish:reboot' >&${cydia[0]}"
        	fi
      	  	exit 0
   	 	else
       		exit 1
   		fi
   	fi
fi


