#!/bin/sh

chk=$(uname -m)

if [[ "$chk" == iPod5* ]] || [[ "$chk" == iPhone4* ]] || [[ "$chk" == iPhone5* ]];then
	rm -f /Library/MobileSubstrate/DynamicLibraries/BackBoardEnv*
	rm -f /usr/lib/libPano.dylib
fi

