#!/bin/sh

chk=$(uname -m)

chown 0:0 /Library/LaunchDaemons/com.ps.panomod.helper.plist
chmod 644 /Library/LaunchDaemons/com.ps.panomod.helper.plist
launchctl load /Library/LaunchDaemons/com.ps.panomod.helper.plist

if [[ "$chk" == iPod5* ]] || [[ "$chk" == iPhone4* ]] || [[ "$chk" == iPhone5* ]] || [[ "$chk" == iPhone6* ]] || [[ "$chk" == iPhone7* ]] || [[ "$chk" == iPad5* ]];then
	rm -f /Library/MobileSubstrate/DynamicLibraries/PanoHook*
	rm -f /Library/MobileSubstrate/DynamicLibraries/actFix*
else
	if [[ "$chk" == iPad* ]];then
		rm -f /Library/MobileSubstrate/DynamicLibraries/actFix*
	fi
	cp /Library/PanoModUI/*.png /System/Library/PrivateFrameworks/PhotoLibrary.framework
fi

killall RootHelper

rm -rf /Library/PanoModUI
