
include ../theos/makefiles/common.mk
export ARCHS = armv7
TWEAK_NAME = BackBoardEnv
BackBoardEnv_FILES = BackBoardEnv.xmi
BackBoardEnv_OBJCFLAGS = -I$(THEOS_PROJECT_DIR) -F$(THEOS_PROJECT_DIR)

include $(THEOS_MAKE_PATH)/tweak.mk

