ARCHS = armv7 arm64

TWEAK_NAME = PanoHook
PanoHook_FILES = PanoHook.xm
PanoHook_LIBRARIES = substrate MobileGestalt
PanoHook_FRAMEWORKS = CoreFoundation IOKit
PanoHook_PRIVATE_FRAMEWORKS = ACTFramework

include ../theos/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
